### ISSUE TITLE
Pool swaps for v3 boosted pools

### ISSUE THREAD

**Issue by agualis** [balancer/frontend-monorepo#106]
- [ ] - Wait for API to have pool id filter in the getSwapPath query: https://github.com/balancer/backend/issues/1162
- [ ] - Refactor implementation to get path from the API passing the list of pool ids required for a swap in a given pool.

**Comment by gmbronco** [comment]
@agualis hey - you can use SOR with poolIds param like so:
```
{
  sorGetSwapPaths(
    ...
    poolIds:["0x3de2...588"]
  ) {
    ...
  }
}
```
