### ISSUE TITLE
Handle dynamic swap fees

### ISSUE THREAD

**Issue by garethfuller** [balancer/frontend-monorepo#140]
For pools where hook. shouldCallComputeDynamicSwapFee == true hide swap fee data and replace with icon that represents dynamic swap fees.

**Comment by uiuxxx** [comment]
Designs:

https://www.figma.com/design/stjMSRgYKmzmau9InfKbCh/V3-new-styles?node-id=7714-455&t=voSnyNAben1LuqkR-1

Swap fees should be positioned last (after any hooks).

Dynamic fees SVG is attached!

[Image](https://github.com/user-attachments/assets/a8bf053d-917c-4449-a2a1-d7376d9e5106)
