### ISSUE TITLE
Hook review support

### ISSUE THREAD

**Issue by garethfuller** [balancer/frontend-monorepo#151]
We need to handle hook reviews in the same way we handle rate provider reviews on pool pages.

- Render the information
- Block actions and display warnings under certain conditions.

Designs: https://www.figma.com/design/97sJd9iKmVWDsPIUdHGxTk/v3-App-Pools-Launch?node-id=0-1&t=FqwfjgPU5WOdvOwr-1

**Comment by garethfuller** [comment]
Pool with hook: http://localhost:3000/pools/sepolia/v3/0x75F49D54978d08E4E76a873dA6c78E8f6b2901C2

**Comment by groninge01** [comment]
@garethfuller how do we handle nested pools with a hook in Pool Contracts?
