### ISSUE TITLE
Bring pool creator

### ISSUE THREAD

**Issue by agualis** [balancer/frontend-monorepo#187]
Pool creator is an standalone project that is currently copy-pasting some of the code from V3 monorepo. We should: 
A. Move the pool creator inside the mono-repo
or
B. Extract am npm library to share the common code that the current pool creator is duplicating.

**Comment by agualis** [comment]
cc @MattPereira

**Comment by garethfuller** [comment]
@MattPereira we're using Turborepo so having different dependencies won't be a problem. They'll just be dependencies of your app.

**Comment by MattPereira** [comment]
oh sweet then I guess decision comes down to if reward of moving scaffold into monorepo is worth the trouble ?
( this is just me guessing :sweat_smile: )

#### Costs
- Vercel deployment would need to be changed 
- Risk of additional complexity as scaffold itself is a yarn workspaces monorepo so may need some re-configuration?

#### Benefits
- Scaffold could borrow things like rpc urls and hooks from v3 FE?
- Fewer balancer repos floating around

**Comment by garethfuller** [comment]
I think eventually pool creation will be brought within the main app and the cost of managing another app within the monorepo for now isn't worth it. We can revisit this later.
