### ISSUE TITLE
Address Xeonus V3 feedback

### ISSUE THREAD

**Issue by agualis** [balancer/frontend-monorepo#218]
Discuss wording and other suggestions: 
https://balancerecosystem.slack.com/archives/C04KJE1U8TU/p1732968937461009

**Comment by Xeonus** [comment]
Suggestions for wording / UX:

- boosted pool text, replace with: `This Boosted pool's underlying mechanics are powered by wrapped Aave tokens, which generate yield from lending activities on the Aave protocol, resulting in continuous appreciation of the pool's total value.`
![Image](https://github.com/user-attachments/assets/e86032c5-9dd9-4ed0-a06c-a3e2f879434b)
- where do we see buffers if they are used?
![Image](https://github.com/user-attachments/assets/f4427cac-f749-4cde-ab05-2f3e04ed2d9c)
- no hook details present on pool overview page (yet)
![Image](https://github.com/user-attachments/assets/7d6f8381-2256-4ac0-a9ca-a4ed8f768039)
- My Portfolio: all mixed, no indication of what is v2 and what is v3, needs a label IMO. See my deployer with lots of positions, impossible to sort stuff
![Image](https://github.com/user-attachments/assets/d7add93f-7f4e-409a-963d-29cae9417848)
- For boosted poos: why are there no APRs on testnet? No tested lending happening? How can we make sure everything will work correctly with rate providers on mainnet?


UI testing:

- Every time I want to swap sepolia ETH to a token I need to sign permit: ETH. I expect this to only be once per token I want to swap to authorize the vault? Is there a mis-label and it should be "sign permit: tokenname"?
![Image](https://github.com/user-attachments/assets/7f3ead6b-677c-4d7a-ac56-e9ca986d2e74)
- Permit 2 breaks [completely for me for this pair](https://mono-test-v3-git-feat-add-liquidity-tabs-balancer.vercel.app/swap/sepolia/0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/0x94a9d9ac8a22534e3faca9f4e7f2e2cf85d5e4c8/0.001), also higher amounts
![Image](https://github.com/user-attachments/assets/9ef1aa70-3e62-416c-9aeb-b65ff295ee5b)
- adds not showing up in "My Transactions", might be data issue
![Image](https://github.com/user-attachments/assets/9917a7c7-765e-4f65-86e5-d3040c08c737)

**Comment by agualis** [comment]
@Xeonus I will move this ticket as done. There are still some pending issues but they are already tracker in other issues. Thanks for reporting! 🙌
