### ISSUE TITLE
Fix button group alignment and width

### ISSUE THREAD

**Issue by agualis** [balancer/frontend-monorepo#245]
![image](https://github.com/user-attachments/assets/79d120db-0a83-4696-adf1-59be95944a83)

probably caused by [this change](https://github.com/balancer/frontend-monorepo/pull/223/files#diff-2f5a010778ece536b620db578fb6c8546fa07093407b73fa3f248a68df2e5ac9)

**Comment by groninge01** [comment]
![image](https://github.com/user-attachments/assets/83a93135-887e-4f7b-b6b3-2499286202ef)
