### ISSUE TITLE
Link to the pool on the LP token

### ISSUE THREAD

**Issue by alter-eggo** [balancer/frontend-monorepo#249]
![Image](https://github.com/user-attachments/assets/74b3824a-f572-4154-b070-81e1f229c457)

**Comment by Lerz-bordev** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Balencer Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
