### ISSUE TITLE
V3: Hook support

### ISSUE THREAD

**Issue by garethfuller** [balancer/frontend-monorepo#29]
There is a pool with a hook on Sepolia - exit fee hook.

**Comment by garethfuller** [comment]
cc @uiuxxx

**Comment by uiuxxx** [comment]
https://www.figma.com/design/97sJd9iKmVWDsPIUdHGxTk/v3-App-Pools-Launch?node-id=0-1&t=FqwfjgPU5WOdvOwr-1

**Comment by garethfuller** [comment]
Pool with hook: http://localhost:3000/pools/sepolia/v3/0x79f53b05828e09ec04f1a028a341cab09591523a

**Comment by garethfuller** [comment]
![Image](https://github.com/user-attachments/assets/cfc27ec8-41a3-473f-a558-ecdbb63cc980)

**Comment by garethfuller** [comment]
http://localhost:3000/pools/sepolia/v3/0x75F49D54978d08E4E76a873dA6c78E8f6b2901C2
