### ISSUE TITLE
Nested pool display

### ISSUE THREAD

**Issue by garethfuller** [balancer/frontend-monorepo#99]
- [ ] Pool detail
- [ ] Pool list

**Comment by garethfuller** [comment]
@uiuxxx do we have designs for nested pools we can link here?

**Comment by garethfuller** [comment]
https://test.balancer.fi/pools/sepolia/v3/0x711fd80b36723bce3b42ad6622903e1e39d911dd

**Comment by uiuxxx** [comment]
Designs are here (I've left them besides the Boosted pools section for easy comparison).

https://www.figma.com/design/97sJd9iKmVWDsPIUdHGxTk/v3-App-Pools-Launch?node-id=4-764&t=7XfkpuJOJYBGX84D-1
